- name: cis-docker-ce-profile
  title: CIS Docker Community Edition
  maintainer: MITRE InSpec Team
  copyright: 
  copyright_email: inspec_support@mitre.org
  license: Apache-2.0
  summary: The CIS Docker Community Edition Benchmark v1.1.0 InSpec profile.
  version: 1.1.0
  clone_url: "git@gitlab.mitre.org:inspec/cis-docker-ce-profile.git"
  source_url: "https://gitlab.mitre.org/inspec/cis-docker-ce-profile"
  
- name: nginx-baseline
  title: DevSec Nginx Baseline
  maintainer: DevSec Hardening Framework Team
  copyright: DevSec Hardening Framework Team
  copyright_email: hello@dev-sec.io
  license: Apache 2 license
  summary: Test-suite for best-practice nginx hardening
  version: 2.0.2
  supports:
    - os-family: unix
  clone_url: "git@gitlab.mitre.org:inspec/nginx-baseline.git"
  source_url: "https://gitlab.mitre.org/inspec/nginx-baseline"
